name: Build and Deploy ASP.Net Core 8 App - CountryWeb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./Country.Web/Country.Web.csproj

      - name: Build
        run: dotnet build ./Country.Web/Country.Web.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Country.Web/Country.Web.csproj -c Release -o ./publish --no-build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: countryweb
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: countryweb

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CountryWeb'
          slot-name: 'Production'
          package: ./publish
